name: bot_io
version: 0.25.3+1-dev
author: Kevin Moore <github@j832.com>
description: A collection of Dart file system helpers built on dart:io
homepage: https://github.com/kevmoo/bot_io.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://kevmoo.github.io/bot_io.dart
dependencies:
  args: '>=0.9.0 <0.11.0'
  bot: '>=0.26.0'
  completion: '>=0.1.0 <0.2.0'
  crypto: '>=0.9.0 <0.10.0'
  git: '>=0.1.0 <0.2.0'
  logging: '>=0.9.0 <0.10.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  hop: '>=0.28.1+2'
  unittest: '>=0.10.0 <0.11.0'
